### ISSUE TITLE
client.conf关于PostUp的问题

### ISSUE THREAD

**Issue by yangtao9808** [lmc999/Wireguard-anti-QOS#1]
这句PostUp = start D:\software\TunSafe\bat\routes-up.bat，无法实现分流，改成PreUp = start D:\software\TunSafe\bat\routes-up.bat就没问题。

**Comment by lmc999** [comment]
我这边没有这个问题出现，如果你修改过可以使用便OK

**Comment by ymcoming** [comment]
装了udp2raw的话，android上的tunsafe还能正常使用吗？没有预加载选项

**Comment by yangtao9808** [comment]
可以正常使用


发自我的 iPhone
